# docker-compose.yml
version: '3'
services:
    pg_backup:
        build: .
        image: pg_backup:latest
        container_name: pg_backup
        environment:
            TZ: Asia/Shanghai
            CRON_TIME: '23 17 * * *'
            INIT_BACKUP: 'true'
            POSTGRES_USER: root
            POSTGRES_PASSWORD: public
            POSTGRES_PORT: 5432
            MAX_BACKUPS: 3
            POSTGRES_HOST: postgres
        volumes:
            - ./pg_backup:/backup
            - ./wait-for-it.sh:/wait-for-it.sh
        command: ["./wait-for-it.sh", "postgres:5432", "--", "./run.sh"]

networks:
    default:
        external:
            name: x
